name: core
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  about:
    path: ../about
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  envied: ^0.3.0+3
  equatable: ^2.0.5
  firebase_crashlytics: ^3.3.5
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  http: ^1.1.0
  movies:
    path: ../movies
  sqflite: ^2.3.0
  tv_series:
    path: ../tv_series

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

flutter: null